name: First Workflow


on: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo 'build'

  test:
    runs-on: windows-latest
    steps:
      - name: Print test - Chrome
        run: echo 'build'
      - name: Print test - edge
        run: echo 'test edge'

  
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo 'deploy'
