name: First Workflow


#on: [push, issues, pull_request]

#only execute the flow when pull_request with an activity type is in opened status
on: 
  pull_request:
    types: opened


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo 'build'

  test:
    runs-on: windows-latest
    steps:
      - name: Print test - Chrome
        run: echo 'build'
      - name: Print test - edge
        run: echo 'test edge'

  
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo 'deploy'
