name: Schedule-Workflow

on:
  push:
  pull_request:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "This workflow was triggered by ${{ github.event_name }} at ${{ github.event.head_commit.timestamp }}"
